### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [ercanersoy/DOS-Coreutils#4]
The program must be compiled with **DJGPP** and optionally should compressed with UPX. **Compreesing**  with UPX is default.

**Comment by ercanersoy** [comment]
This issue has been solved.

**Comment by javiergutierrezchamorro** [comment]
Not solved. Compressing is still misspelled.
Compressing and not Compreesing.

**Comment by ercanersoy** [comment]
I have fixed it.

**Comment by javiergutierrezchamorro** [comment]
Not solved. Now it says again DJGPP.

**Comment by ercanersoy** [comment]
I fixed it.
